// Generated by CoffeeScript 1.9.1
(function() {
  window.global = {
    wd: '/',
    ls: [],
    editingFile: '',
    errDict: {
      '-404': '文件不存在。',
      '-505': '文件已存在。',
      '-506': '找不到目录。'
    },
    openfile: function(path) {
      return $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'open',
          file: path
        },
        dataType: 'json',
        success: function(data) {
          var i, j, namespan, operation_text, parent_path, ref, sizeText, tp, typeText;
          console.log('Response Received!');
          console.log(data);
          $('#ls-view').empty();
          $('#path-view').empty();
          parent_path = window.global.wd.substring(0, window.global.wd.length - 1);
          console.log('parent_path: ' + parent_path);
          window.global.wd = path + '/';
          if (window.global.wd !== '/') {
            $('#ls-view').append('<tr><td><span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span></td><td><a href="#" onclick="window.global.returnParent()">..</a></td><td> </td><td> </td><td> </td><td> </td><td> </td></tr>');
          }
          if (data['files'].length > 0) {
            for (i = j = 0, ref = data['files'].length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
              tp = data['files'][i]['type'];
              typeText = '';
              if (tp === 'd') {
                typeText = '<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>';
              } else {
                typeText = '<span class="glyphicon glyphicon-file" aria-hidden="true"></span>';
              }
              if (data['files'][i]['size'] > 1000000) {
                sizeText = (data['files'][i]['size'] / 1000000).toString() + ' M';
              } else if (data['files'][i]['size'] > 1000) {
                sizeText = (data['files'][i]['size'] / 1000).toString() + ' K';
              } else {
                sizeText = data['files'][i]['size'].toString();
              }
              if (tp === 'd') {
                namespan = '<a href="#" onclick="window.global.openfile(\'' + (path || '') + '/' + data['files'][i]['name'] + '\')">' + data['files'][i]['name'] + '</a>';
              } else {
                namespan = '<a href="#" data-toggle="modal" data-target="#myModal" onclick="window.global.editfile(\'' + (path || '') + '/' + data['files'][i]['name'] + '\')">' + data['files'][i]['name'] + '</a>';
              }
              operation_text = '<a href="#" onclick="window.global.deleteFile(\'' + parent_path + '/' + data['files'][i]['name'] + '\')"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>';
              operation_text += '';
              $('#ls-view').append('<tr>' + '<td>' + typeText + '</td>' + '<td>' + namespan + '</td>' + '<td>' + sizeText + '</td>' + '<td>' + data['files'][i]['lac'] + '</td>' + '<td>' + data['files'][i]['lup'] + '</td>' + '<td>' + data['files'][i]['idx'] + '</td>' + '<td>' + operation_text + '</td>' + '</tr>');
            }
          }
          $('#create-folder-parent').empty();
          $('#create-folder-parent').append(window.global.wd);
          $('#path-view').append(window.global.wd);
          return 0;
        }
      });
    },
    returnParent: function() {
      var parent_path;
      if (window.global.wd === '/') {
        return;
      }
      parent_path = window.global.wd.substring(0, window.global.wd.length - 1);
      parent_path = parent_path.substring(0, parent_path.lastIndexOf('/'));
      console.log('parent_path: ' + parent_path);
      return $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'open',
          file: parent_path
        },
        dataType: 'json',
        success: function(data) {
          var i, j, namespan, operation_text, ref, sizeText, tp, typeText;
          console.log('Response Received!');
          console.log(data);
          $('#ls-view').empty();
          $('#path-view').empty();
          $('#path-view').append(parent_path + '/');
          window.global.wd = parent_path + '/';
          if (window.global.wd !== '/') {
            $('#ls-view').append('<tr><td><span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span></td><td><a href="#" onclick="window.global.returnParent()">..</a></td><td> </td><td> </td><td> </td><td> </td><td> </td></tr>');
          }
          if (data['files'].length > 0) {
            for (i = j = 0, ref = data['files'].length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
              tp = data['files'][i]['type'];
              typeText = '';
              if (tp === 'd') {
                typeText = '<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>';
              } else {
                typeText = '<span class="glyphicon glyphicon-file" aria-hidden="true"></span>';
              }
              if (data['files'][i]['size'] > 1000000) {
                sizeText = (data['files'][i]['size'] / 1000000).toString() + ' M';
              } else if (data['files'][i]['size'] > 1000) {
                sizeText = (data['files'][i]['size'] / 1000).toString() + ' K';
              } else {
                sizeText = data['files'][i]['size'].toString();
              }
              if (tp === 'd') {
                namespan = '<a href="#" onclick="window.global.openfile(\'' + parent_path + '/' + data['files'][i]['name'] + '\')">' + data['files'][i]['name'] + '</a>';
              } else {
                namespan = '<a href="#" data-toggle="modal" data-target="#myModal" onclick="window.global.editfile(\'' + parent_path + '/' + data['files'][i]['name'] + '\')">' + data['files'][i]['name'] + '</a>';
              }
              operation_text = '<a href="#" onclick="window.global.deleteFile(\'' + parent_path + '/' + data['files'][i]['name'] + '\')"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>';
              $('#ls-view').append('<tr>' + '<td>' + typeText + '</td>' + '<td>' + namespan + '</td>' + '<td>' + sizeText + '</td>' + '<td>' + data['files'][i]['lac'] + '</td>' + '<td>' + data['files'][i]['lup'] + '</td>' + '<td>' + data['files'][i]['idx'] + '</td>' + '<td>' + operation_text + '</td>' + '</tr>');
            }
          }
          $('#create-folder-parent').empty();
          $('#create-folder-parent').append(window.global.wd);
          return 0;
        }
      });
    },
    editfile: function(filepath) {
      window.global.editingFile = '';
      console.log('Editing file: ' + filepath);
      $('#edit-file-title').empty();
      $('#edit-file-title').append('编辑文件：' + filepath);
      $('#edit-file-content').val('');
      return $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'read',
          path: filepath
        },
        dataType: 'json',
        success: function(res) {
          $('#edit-file-content').val(res['content']);
          return window.global.editingFile = filepath;
        }
      });
    },
    deleteFile: function(filepath) {
      var conf;
      conf = confirm('是否确定删除此文件？');
      if (conf !== true) {
        return 0;
      }
      $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'delete',
          path: filepath
        },
        dataType: 'json',
        success: function(res) {
          if (res.code !== 0) {
            alert('哎呀，删除失败：' + window.global.errDict[code]);
            return 0;
          }
          window.global.openfile(window.global.wd.substring(0, window.global.wd.length - 1));
          return 0;
        }
      });
      return 0;
    }
  };

  $(document).ready(function() {
    window.global.openfile('');
    $('#btn-new-folder').click(function(event) {
      var filename, newFileUrl;
      filename = $('#create-file-input').val();
      if (filename === '') {
        alert('文件或文件夹名不能为空…… _(:з」∠)_');
        return;
      }
      if (filename.indexOf('/') !== -1 || filename.indexOf('*') !== -1 || filename.indexOf('?') !== -1 || filename.indexOf('<') !== -1 || filename.indexOf('>') !== -1 || filename.indexOf(':') !== -1 || filename.indexOf('|') !== -1 || filename.indexOf('\\') !== -1 || filename.indexOf('"') !== -1) {
        alert('请确定你的文件或文件夹名是合法的…… _(:з」∠)_');
        return;
      }
      if (filename.lastIndexOf('.') === (filename.length - 1)) {
        alert('请确定你的文件或文件夹名是合法的…… _(:з」∠)_');
        return;
      }
      newFileUrl = window.global.wd + $('#create-file-input').val();
      console.log('Creating folder: %s', newFileUrl);
      return $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'create',
          path: newFileUrl,
          type: 'd'
        },
        dataType: 'json',
        success: function(res) {
          var code;
          code = res.code;
          if (code !== 0) {
            alert('哎呀，出错了：\n' + (window.global.errDict[code.toString()] || ("未知错误……" + code.toString())));
            return 1;
          } else {
            window.global.openfile(window.global.wd.substring(0, window.global.wd.length - 1));
            return 0;
          }
        }
      });
    });
    $('#btn-new-regfile').click(function(event) {
      var filename, newFileUrl;
      filename = $('#create-file-input').val();
      if (filename === '') {
        alert('文件或文件夹名不能为空…… _(:з」∠)_');
        return;
      }
      if (filename.indexOf('/') !== -1 || filename.indexOf('*') !== -1 || filename.indexOf('?') !== -1 || filename.indexOf('<') !== -1 || filename.indexOf('>') !== -1 || filename.indexOf(':') !== -1 || filename.indexOf('|') !== -1 || filename.indexOf('\\') !== -1 || filename.indexOf('"') !== -1) {
        alert('请确定你的文件或文件夹名是合法的…… _(:з」∠)_');
        return;
      }
      if (filename.lastIndexOf('.') === (filename.length - 1)) {
        alert('请确定你的文件或文件夹名是合法的…… _(:з」∠)_');
        return;
      }
      newFileUrl = window.global.wd + $('#create-file-input').val();
      console.log('Creating file: %s', newFileUrl);
      return $.ajax({
        url: '/operation',
        type: 'POST',
        data: {
          operation: 'create',
          path: newFileUrl,
          type: '-'
        },
        dataType: 'json',
        success: function(res) {
          var code;
          code = res.code;
          if (code !== 0) {
            alert('哎呀，出错了：\n' + (window.global.errDict[code.toString()] || ("未知错误……" + code.toString())));
            return 1;
          } else {
            window.global.openfile(window.global.wd.substring(0, window.global.wd.length - 1));
            return 0;
          }
        }
      });
    });
    $('#edit-file-btn-close').click(function(event) {
      window.global.editingFile = '';
      return window.global.openfile(window.global.wd.substring(0, window.global.wd.length - 1));
    });
    $('#edit-file-btn-save').click(function(evnet) {
      var filepath, writeContent;
      filepath = window.global.editingFile;
      writeContent = $('#edit-file-content').val() || '';
      console.log('Writing file: ' + filepath);
      console.log('Writing Content: ' + writeContent);
      $.ajax({
        url: '/operation',
        type: 'POST',
        dataType: 'json',
        data: {
          operation: 'write',
          path: filepath,
          content: writeContent
        },
        success: function(res) {
          var code;
          code = res.code;
          if (code === 0) {
            alert('保存成功~');
          } else {
            alert('哎呀，保存失败：' + window.global.errDict[code]);
          }
          return 0;
        }
      });
      return 0;
    });
    return 0;
  });

}).call(this);

//# sourceMappingURL=fs.js.map
